#!/bin/sh

# tfwrap - Minimalist Terraform wrapper, similar to tfenv

set -eu

# Common functions

err() {
	echo "tfwrap:" "$@" >&2
	exit 1
}

debug() {
	if [ -n "${TFWRAP_DEBUG:-}" ]; then
		echo "tfwrap:" "$@" >&2
	fi
}

# Reading Terraform version file

[ -f ".terraform-version" ] || err "No such file: .terrform-version"
[ -r ".terraform-version" ] || err "File is not readable: .terrform-version"

terraform_basedir="$HOME/.local/terraform"
tfver="$(tr -d '[:blank:]' < .terraform-version)"

[ -n "$tfver" ] || err "Terraform version file is empty: .terraform-version"

debug "Selected Terraform version: $tfver"

# Running Terraform binary

terraform_bin="${terraform_basedir}/${tfver:-"default"}/terraform"

debug "Trying to use Terraform binary: $terraform_bin"

[ -x "$terraform_bin" ] || err "Terraform binary not found: $terraform_bin" 

debug "Executing:" "$terraform_bin" "$@"

exec "$terraform_bin" "$@"
